# Auto-generated parser for missoula_landfill
# Generated by TemplateWizard

import fitz  # PyMuPDF
import re

def extract_pdf_text(pdf_path):
    doc = fitz.open(pdf_path)
    pages = []
    for i, page in enumerate(doc):
        text = page.get_text("text")
        pages.append((i + 1, text))
    doc.close()
    return pages


def parse_invoice(pdf_path):
    pages = extract_pdf_text(pdf_path)
    results = []

    for page_num, text in pages:
        inv = {
            "vendor": detect_vendor_name(text),
            "invoice_number": detect_invoice_number(text),
            "jobname": detect_jobname(text),
            "date": detect_invoice_date(text),
            "total": detect_invoice_total(text),
            "work_number": detect_work_number(text),
            "page": page_num,
        }
        results.append(inv)

    return results[0] if len(results) == 1 else results


def detect_vendor_name(text):
    m = re.search(r"12,700\s*([^\n]+)", text, re.MULTILINE)
    if m:
        return m.group(1).strip()
    return "MISSOULA LANDFILL"

def detect_invoice_number(text):
    m = re.search(r"1636470\s*([^\n]+)", text, re.MULTILINE)
    if m:
        return m.group(1).strip()
    return ""
def detect_invoice_date(text):
    m = re.search(r"MISSOULA,\ MT\ \ 59808\s*([^\n]+)", text, re.MULTILINE)
    if m:
        return m.group(1).strip()
    return ""
def detect_invoice_total(text):
    m = re.search(r"\$\s*([^\n]+)", text, re.MULTILINE)
    if m:
        return m.group(1).strip()
    return ""
def detect_jobname(text):
    m = re.search(r"4/17/25\ \ \ 2:08\ pm\s*([^\n]+)", text, re.MULTILINE)
    if m:
        return m.group(1).strip()
    return ""
def detect_work_number(text):
    m = re.search(r"BOYCE\s*([^\n]+)", text, re.MULTILINE)
    if m:
        return m.group(1).strip()
    return ""
